service: take-home-assessment

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  timeout: 30

functions:
  get_all_orders:
    handler: handler.get_all_orders
    events:
      - httpApi:
          path: /orders
          method: get
  get_service:
    handler: handler.get_service
    events:
      - httpApi:
          path: /services/{id}/
          method: get
  get_all_services:
      handler: handler.get_all_services
      events:
        - httpApi:
            path: /services
            method: get
  add_service:
    handler: handler.add_service
    events:
      - httpApi:
          path: /services
          method: post
  add_order:
    handler: handler.add_order
    events:
      - httpApi:
          path: /orders
          method: post
  update_order:
    handler: handler.update_order
    events:
      - httpApi:
          path: /orders/{id}/
          method: patch
  delete_order:
    handler: handler.delete_order
    events:
      - httpApi:
          path: /orders/{id}/
          method: delete
